module.exports.TOKEN_UPDATE = 'TOKEN_UPDATE'

module.exports.NAMESPACE_BROADCAST = 'BROADCAST'
module.exports.BROADCAST_START = 'BROADCAST_START'
module.exports.BROADCAST_END = 'BROADCAST_END'
module.exports.BROADCAST_UPDATE = 'BROADCAST_UPDATE'
